// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddFriendArgs {
    pub player_entity_id: u64,
}

impl From<AddFriendArgs> for super::Reducer {
    fn from(args: AddFriendArgs) -> Self {
        Self::AddFriend {
            player_entity_id: args.player_entity_id,
        }
    }
}

impl __sdk::InModule for AddFriendArgs {
    type Module = super::RemoteModule;
}

pub struct AddFriendCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_friend`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_friend {
    /// Request that the remote module invoke the reducer `add_friend` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_add_friend`] callbacks.
    fn add_friend(&self, player_entity_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `add_friend`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AddFriendCallbackId`] can be passed to [`Self::remove_on_add_friend`]
    /// to cancel the callback.
    fn on_add_friend(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> AddFriendCallbackId;
    /// Cancel a callback previously registered by [`Self::on_add_friend`],
    /// causing it not to run in the future.
    fn remove_on_add_friend(&self, callback: AddFriendCallbackId);
}

impl add_friend for super::RemoteReducers {
    fn add_friend(&self, player_entity_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("add_friend", AddFriendArgs { player_entity_id })
    }
    fn on_add_friend(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> AddFriendCallbackId {
        AddFriendCallbackId(self.imp.on_reducer(
            "add_friend",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AddFriend { player_entity_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_entity_id)
            }),
        ))
    }
    fn remove_on_add_friend(&self, callback: AddFriendCallbackId) {
        self.imp.remove_on_reducer("add_friend", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `add_friend`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_add_friend {
    /// Set the call-reducer flags for the reducer `add_friend` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn add_friend(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_add_friend for super::SetReducerFlags {
    fn add_friend(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("add_friend", flags);
    }
}
