// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AdminRecalculateEmpireUpkeepsArgs {}

impl From<AdminRecalculateEmpireUpkeepsArgs> for super::Reducer {
    fn from(args: AdminRecalculateEmpireUpkeepsArgs) -> Self {
        Self::AdminRecalculateEmpireUpkeeps
    }
}

impl __sdk::InModule for AdminRecalculateEmpireUpkeepsArgs {
    type Module = super::RemoteModule;
}

pub struct AdminRecalculateEmpireUpkeepsCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `admin_recalculate_empire_upkeeps`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait admin_recalculate_empire_upkeeps {
    /// Request that the remote module invoke the reducer `admin_recalculate_empire_upkeeps` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_admin_recalculate_empire_upkeeps`] callbacks.
    fn admin_recalculate_empire_upkeeps(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `admin_recalculate_empire_upkeeps`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`AdminRecalculateEmpireUpkeepsCallbackId`] can be passed to [`Self::remove_on_admin_recalculate_empire_upkeeps`]
    /// to cancel the callback.
    fn on_admin_recalculate_empire_upkeeps(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminRecalculateEmpireUpkeepsCallbackId;
    /// Cancel a callback previously registered by [`Self::on_admin_recalculate_empire_upkeeps`],
    /// causing it not to run in the future.
    fn remove_on_admin_recalculate_empire_upkeeps(
        &self,
        callback: AdminRecalculateEmpireUpkeepsCallbackId,
    );
}

impl admin_recalculate_empire_upkeeps for super::RemoteReducers {
    fn admin_recalculate_empire_upkeeps(&self) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "admin_recalculate_empire_upkeeps",
            AdminRecalculateEmpireUpkeepsArgs {},
        )
    }
    fn on_admin_recalculate_empire_upkeeps(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> AdminRecalculateEmpireUpkeepsCallbackId {
        AdminRecalculateEmpireUpkeepsCallbackId(self.imp.on_reducer(
            "admin_recalculate_empire_upkeeps",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::AdminRecalculateEmpireUpkeeps {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_admin_recalculate_empire_upkeeps(
        &self,
        callback: AdminRecalculateEmpireUpkeepsCallbackId,
    ) {
        self.imp
            .remove_on_reducer("admin_recalculate_empire_upkeeps", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `admin_recalculate_empire_upkeeps`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_admin_recalculate_empire_upkeeps {
    /// Set the call-reducer flags for the reducer `admin_recalculate_empire_upkeeps` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn admin_recalculate_empire_upkeeps(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_admin_recalculate_empire_upkeeps for super::SetReducerFlags {
    fn admin_recalculate_empire_upkeeps(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("admin_recalculate_empire_upkeeps", flags);
    }
}
