// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct BlockPlayerArgs {
    pub player_entity_id: u64,
}

impl From<BlockPlayerArgs> for super::Reducer {
    fn from(args: BlockPlayerArgs) -> Self {
        Self::BlockPlayer {
            player_entity_id: args.player_entity_id,
        }
    }
}

impl __sdk::InModule for BlockPlayerArgs {
    type Module = super::RemoteModule;
}

pub struct BlockPlayerCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `block_player`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait block_player {
    /// Request that the remote module invoke the reducer `block_player` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_block_player`] callbacks.
    fn block_player(&self, player_entity_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `block_player`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`BlockPlayerCallbackId`] can be passed to [`Self::remove_on_block_player`]
    /// to cancel the callback.
    fn on_block_player(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> BlockPlayerCallbackId;
    /// Cancel a callback previously registered by [`Self::on_block_player`],
    /// causing it not to run in the future.
    fn remove_on_block_player(&self, callback: BlockPlayerCallbackId);
}

impl block_player for super::RemoteReducers {
    fn block_player(&self, player_entity_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("block_player", BlockPlayerArgs { player_entity_id })
    }
    fn on_block_player(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> BlockPlayerCallbackId {
        BlockPlayerCallbackId(self.imp.on_reducer(
            "block_player",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::BlockPlayer { player_entity_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_entity_id)
            }),
        ))
    }
    fn remove_on_block_player(&self, callback: BlockPlayerCallbackId) {
        self.imp.remove_on_reducer("block_player", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `block_player`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_block_player {
    /// Set the call-reducer flags for the reducer `block_player` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn block_player(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_block_player for super::SetReducerFlags {
    fn block_player(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("block_player", flags);
    }
}
