// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::blocked_player_state_type::BlockedPlayerState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `blocked_player_state`.
///
/// Obtain a handle from the [`BlockedPlayerStateTableAccess::blocked_player_state`] method on [`super::RemoteTables`],
/// like `ctx.db.blocked_player_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.blocked_player_state().on_insert(...)`.
pub struct BlockedPlayerStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<BlockedPlayerState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `blocked_player_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait BlockedPlayerStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`BlockedPlayerStateTableHandle`], which mediates access to the table `blocked_player_state`.
    fn blocked_player_state(&self) -> BlockedPlayerStateTableHandle<'_>;
}

impl BlockedPlayerStateTableAccess for super::RemoteTables {
    fn blocked_player_state(&self) -> BlockedPlayerStateTableHandle<'_> {
        BlockedPlayerStateTableHandle {
            imp: self
                .imp
                .get_table::<BlockedPlayerState>("blocked_player_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct BlockedPlayerStateInsertCallbackId(__sdk::CallbackId);
pub struct BlockedPlayerStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for BlockedPlayerStateTableHandle<'ctx> {
    type Row = BlockedPlayerState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = BlockedPlayerState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = BlockedPlayerStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockedPlayerStateInsertCallbackId {
        BlockedPlayerStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: BlockedPlayerStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = BlockedPlayerStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> BlockedPlayerStateDeleteCallbackId {
        BlockedPlayerStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: BlockedPlayerStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<BlockedPlayerState>("blocked_player_state");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<BlockedPlayerState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<BlockedPlayerState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}
