// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::direct_message_state_type::DirectMessageState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `direct_message_state`.
///
/// Obtain a handle from the [`DirectMessageStateTableAccess::direct_message_state`] method on [`super::RemoteTables`],
/// like `ctx.db.direct_message_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_message_state().on_insert(...)`.
pub struct DirectMessageStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<DirectMessageState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `direct_message_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait DirectMessageStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`DirectMessageStateTableHandle`], which mediates access to the table `direct_message_state`.
    fn direct_message_state(&self) -> DirectMessageStateTableHandle<'_>;
}

impl DirectMessageStateTableAccess for super::RemoteTables {
    fn direct_message_state(&self) -> DirectMessageStateTableHandle<'_> {
        DirectMessageStateTableHandle {
            imp: self
                .imp
                .get_table::<DirectMessageState>("direct_message_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct DirectMessageStateInsertCallbackId(__sdk::CallbackId);
pub struct DirectMessageStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for DirectMessageStateTableHandle<'ctx> {
    type Row = DirectMessageState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = DirectMessageState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = DirectMessageStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectMessageStateInsertCallbackId {
        DirectMessageStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: DirectMessageStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = DirectMessageStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> DirectMessageStateDeleteCallbackId {
        DirectMessageStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: DirectMessageStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<DirectMessageState>("direct_message_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct DirectMessageStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for DirectMessageStateTableHandle<'ctx> {
    type UpdateCallbackId = DirectMessageStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> DirectMessageStateUpdateCallbackId {
        DirectMessageStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: DirectMessageStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<DirectMessageState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<DirectMessageState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `direct_message_state`,
/// which allows point queries on the field of the same name
/// via the [`DirectMessageStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.direct_message_state().entity_id().find(...)`.
pub struct DirectMessageStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<DirectMessageState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> DirectMessageStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `direct_message_state`.
    pub fn entity_id(&self) -> DirectMessageStateEntityIdUnique<'ctx> {
        DirectMessageStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> DirectMessageStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<DirectMessageState> {
        self.imp.find(col_val)
    }
}
