// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct DirectMessageState {
    pub entity_id: u64,
    pub username: String,
    pub title_id: i32,
    pub sender_entity_id: u64,
    pub receiver_entity_id: u64,
    pub text: String,
    pub timestamp: i32,
}

impl __sdk::InModule for DirectMessageState {
    type Module = super::RemoteModule;
}
