// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireTakeEmperorshipArgs {}

impl From<EmpireTakeEmperorshipArgs> for super::Reducer {
    fn from(args: EmpireTakeEmperorshipArgs) -> Self {
        Self::EmpireTakeEmperorship
    }
}

impl __sdk::InModule for EmpireTakeEmperorshipArgs {
    type Module = super::RemoteModule;
}

pub struct EmpireTakeEmperorshipCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_take_emperorship`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_take_emperorship {
    /// Request that the remote module invoke the reducer `empire_take_emperorship` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_empire_take_emperorship`] callbacks.
    fn empire_take_emperorship(&self) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `empire_take_emperorship`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EmpireTakeEmperorshipCallbackId`] can be passed to [`Self::remove_on_empire_take_emperorship`]
    /// to cancel the callback.
    fn on_empire_take_emperorship(
        &self,
        callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EmpireTakeEmperorshipCallbackId;
    /// Cancel a callback previously registered by [`Self::on_empire_take_emperorship`],
    /// causing it not to run in the future.
    fn remove_on_empire_take_emperorship(&self, callback: EmpireTakeEmperorshipCallbackId);
}

impl empire_take_emperorship for super::RemoteReducers {
    fn empire_take_emperorship(&self) -> __sdk::Result<()> {
        self.imp
            .call_reducer("empire_take_emperorship", EmpireTakeEmperorshipArgs {})
    }
    fn on_empire_take_emperorship(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext) + Send + 'static,
    ) -> EmpireTakeEmperorshipCallbackId {
        EmpireTakeEmperorshipCallbackId(self.imp.on_reducer(
            "empire_take_emperorship",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EmpireTakeEmperorship {},
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx)
            }),
        ))
    }
    fn remove_on_empire_take_emperorship(&self, callback: EmpireTakeEmperorshipCallbackId) {
        self.imp
            .remove_on_reducer("empire_take_emperorship", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `empire_take_emperorship`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_empire_take_emperorship {
    /// Set the call-reducer flags for the reducer `empire_take_emperorship` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn empire_take_emperorship(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_empire_take_emperorship for super::SetReducerFlags {
    fn empire_take_emperorship(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("empire_take_emperorship", flags);
    }
}
