// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireRenameArgs {
    pub new_name: String,
}

impl From<EmpireRenameArgs> for super::Reducer {
    fn from(args: EmpireRenameArgs) -> Self {
        Self::EmpireRename {
            new_name: args.new_name,
        }
    }
}

impl __sdk::InModule for EmpireRenameArgs {
    type Module = super::RemoteModule;
}

pub struct EmpireRenameCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_rename`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_rename {
    /// Request that the remote module invoke the reducer `empire_rename` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_empire_rename`] callbacks.
    fn empire_rename(&self, new_name: String) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `empire_rename`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EmpireRenameCallbackId`] can be passed to [`Self::remove_on_empire_rename`]
    /// to cancel the callback.
    fn on_empire_rename(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> EmpireRenameCallbackId;
    /// Cancel a callback previously registered by [`Self::on_empire_rename`],
    /// causing it not to run in the future.
    fn remove_on_empire_rename(&self, callback: EmpireRenameCallbackId);
}

impl empire_rename for super::RemoteReducers {
    fn empire_rename(&self, new_name: String) -> __sdk::Result<()> {
        self.imp
            .call_reducer("empire_rename", EmpireRenameArgs { new_name })
    }
    fn on_empire_rename(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &String) + Send + 'static,
    ) -> EmpireRenameCallbackId {
        EmpireRenameCallbackId(self.imp.on_reducer(
            "empire_rename",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::EmpireRename { new_name },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, new_name)
            }),
        ))
    }
    fn remove_on_empire_rename(&self, callback: EmpireRenameCallbackId) {
        self.imp.remove_on_reducer("empire_rename", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `empire_rename`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_empire_rename {
    /// Set the call-reducer flags for the reducer `empire_rename` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn empire_rename(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_empire_rename for super::SetReducerFlags {
    fn empire_rename(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("empire_rename", flags);
    }
}
