// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EmpireMoveCapitalArgs {
    pub target_claim_entity_id: u64,
}

impl From<EmpireMoveCapitalArgs> for super::Reducer {
    fn from(args: EmpireMoveCapitalArgs) -> Self {
        Self::EmpireMoveCapital {
            target_claim_entity_id: args.target_claim_entity_id,
        }
    }
}

impl __sdk::InModule for EmpireMoveCapitalArgs {
    type Module = super::RemoteModule;
}

pub struct EmpireMoveCapitalCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `empire_move_capital`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait empire_move_capital {
    /// Request that the remote module invoke the reducer `empire_move_capital` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_empire_move_capital`] callbacks.
    fn empire_move_capital(&self, target_claim_entity_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `empire_move_capital`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`EmpireMoveCapitalCallbackId`] can be passed to [`Self::remove_on_empire_move_capital`]
    /// to cancel the callback.
    fn on_empire_move_capital(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> EmpireMoveCapitalCallbackId;
    /// Cancel a callback previously registered by [`Self::on_empire_move_capital`],
    /// causing it not to run in the future.
    fn remove_on_empire_move_capital(&self, callback: EmpireMoveCapitalCallbackId);
}

impl empire_move_capital for super::RemoteReducers {
    fn empire_move_capital(&self, target_claim_entity_id: u64) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "empire_move_capital",
            EmpireMoveCapitalArgs {
                target_claim_entity_id,
            },
        )
    }
    fn on_empire_move_capital(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> EmpireMoveCapitalCallbackId {
        EmpireMoveCapitalCallbackId(self.imp.on_reducer(
            "empire_move_capital",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer:
                                super::Reducer::EmpireMoveCapital {
                                    target_claim_entity_id,
                                },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, target_claim_entity_id)
            }),
        ))
    }
    fn remove_on_empire_move_capital(&self, callback: EmpireMoveCapitalCallbackId) {
        self.imp
            .remove_on_reducer("empire_move_capital", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `empire_move_capital`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_empire_move_capital {
    /// Set the call-reducer flags for the reducer `empire_move_capital` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn empire_move_capital(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_empire_move_capital for super::SetReducerFlags {
    fn empire_move_capital(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("empire_move_capital", flags);
    }
}
