// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::friends_state_type::FriendsState;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `friends_state`.
///
/// Obtain a handle from the [`FriendsStateTableAccess::friends_state`] method on [`super::RemoteTables`],
/// like `ctx.db.friends_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.friends_state().on_insert(...)`.
pub struct FriendsStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<FriendsState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `friends_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait FriendsStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`FriendsStateTableHandle`], which mediates access to the table `friends_state`.
    fn friends_state(&self) -> FriendsStateTableHandle<'_>;
}

impl FriendsStateTableAccess for super::RemoteTables {
    fn friends_state(&self) -> FriendsStateTableHandle<'_> {
        FriendsStateTableHandle {
            imp: self.imp.get_table::<FriendsState>("friends_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct FriendsStateInsertCallbackId(__sdk::CallbackId);
pub struct FriendsStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for FriendsStateTableHandle<'ctx> {
    type Row = FriendsState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = FriendsState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = FriendsStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FriendsStateInsertCallbackId {
        FriendsStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: FriendsStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = FriendsStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> FriendsStateDeleteCallbackId {
        FriendsStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: FriendsStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<FriendsState>("friends_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct FriendsStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for FriendsStateTableHandle<'ctx> {
    type UpdateCallbackId = FriendsStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> FriendsStateUpdateCallbackId {
        FriendsStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: FriendsStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<FriendsState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<FriendsState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `friends_state`,
/// which allows point queries on the field of the same name
/// via the [`FriendsStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.friends_state().entity_id().find(...)`.
pub struct FriendsStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<FriendsState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> FriendsStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `friends_state`.
    pub fn entity_id(&self) -> FriendsStateEntityIdUnique<'ctx> {
        FriendsStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> FriendsStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<FriendsState> {
        self.imp.find(col_val)
    }
}
