// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RemoveFriendArgs {
    pub player_entity_id: u64,
}

impl From<RemoveFriendArgs> for super::Reducer {
    fn from(args: RemoveFriendArgs) -> Self {
        Self::RemoveFriend {
            player_entity_id: args.player_entity_id,
        }
    }
}

impl __sdk::InModule for RemoveFriendArgs {
    type Module = super::RemoteModule;
}

pub struct RemoveFriendCallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `remove_friend`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait remove_friend {
    /// Request that the remote module invoke the reducer `remove_friend` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_remove_friend`] callbacks.
    fn remove_friend(&self, player_entity_id: u64) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `remove_friend`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`RemoveFriendCallbackId`] can be passed to [`Self::remove_on_remove_friend`]
    /// to cancel the callback.
    fn on_remove_friend(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> RemoveFriendCallbackId;
    /// Cancel a callback previously registered by [`Self::on_remove_friend`],
    /// causing it not to run in the future.
    fn remove_on_remove_friend(&self, callback: RemoveFriendCallbackId);
}

impl remove_friend for super::RemoteReducers {
    fn remove_friend(&self, player_entity_id: u64) -> __sdk::Result<()> {
        self.imp
            .call_reducer("remove_friend", RemoveFriendArgs { player_entity_id })
    }
    fn on_remove_friend(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &u64) + Send + 'static,
    ) -> RemoveFriendCallbackId {
        RemoveFriendCallbackId(self.imp.on_reducer(
            "remove_friend",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::RemoveFriend { player_entity_id },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, player_entity_id)
            }),
        ))
    }
    fn remove_on_remove_friend(&self, callback: RemoveFriendCallbackId) {
        self.imp.remove_on_reducer("remove_friend", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `remove_friend`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_remove_friend {
    /// Set the call-reducer flags for the reducer `remove_friend` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn remove_friend(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_remove_friend for super::SetReducerFlags {
    fn remove_friend(&self, flags: __ws::CallReducerFlags) {
        self.imp.set_call_reducer_flags("remove_friend", flags);
    }
}
