// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::visibility_state_type::VisibilityState;
use super::visibility_type_type::VisibilityType;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visibility_state`.
///
/// Obtain a handle from the [`VisibilityStateTableAccess::visibility_state`] method on [`super::RemoteTables`],
/// like `ctx.db.visibility_state()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visibility_state().on_insert(...)`.
pub struct VisibilityStateTableHandle<'ctx> {
    imp: __sdk::TableHandle<VisibilityState>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visibility_state`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibilityStateTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibilityStateTableHandle`], which mediates access to the table `visibility_state`.
    fn visibility_state(&self) -> VisibilityStateTableHandle<'_>;
}

impl VisibilityStateTableAccess for super::RemoteTables {
    fn visibility_state(&self) -> VisibilityStateTableHandle<'_> {
        VisibilityStateTableHandle {
            imp: self.imp.get_table::<VisibilityState>("visibility_state"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibilityStateInsertCallbackId(__sdk::CallbackId);
pub struct VisibilityStateDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibilityStateTableHandle<'ctx> {
    type Row = VisibilityState;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = VisibilityState> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibilityStateInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibilityStateInsertCallbackId {
        VisibilityStateInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibilityStateInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibilityStateDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibilityStateDeleteCallbackId {
        VisibilityStateDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibilityStateDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<VisibilityState>("visibility_state");
    _table.add_unique_constraint::<u64>("entity_id", |row| &row.entity_id);
}
pub struct VisibilityStateUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibilityStateTableHandle<'ctx> {
    type UpdateCallbackId = VisibilityStateUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibilityStateUpdateCallbackId {
        VisibilityStateUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibilityStateUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<VisibilityState>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<VisibilityState>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `entity_id` unique index on the table `visibility_state`,
/// which allows point queries on the field of the same name
/// via the [`VisibilityStateEntityIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visibility_state().entity_id().find(...)`.
pub struct VisibilityStateEntityIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<VisibilityState, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibilityStateTableHandle<'ctx> {
    /// Get a handle on the `entity_id` unique index on the table `visibility_state`.
    pub fn entity_id(&self) -> VisibilityStateEntityIdUnique<'ctx> {
        VisibilityStateEntityIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("entity_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibilityStateEntityIdUnique<'ctx> {
    /// Find the subscribed row whose `entity_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<VisibilityState> {
        self.imp.find(col_val)
    }
}
