// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::small_hex_tile_message_type::SmallHexTileMessage;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct EnemySpawnLootRequest {
    pub enemy_type: i32,
    pub player_entity_id: u64,
    pub loot_coordinates: SmallHexTileMessage,
}

impl __sdk::InModule for EnemySpawnLootRequest {
    type Module = super::RemoteModule;
}
