// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::combat_action_desc_v_2_type::CombatActionDescV2;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ImportCombatActionDescV2Args {
    pub records: Vec<CombatActionDescV2>,
}

impl From<ImportCombatActionDescV2Args> for super::Reducer {
    fn from(args: ImportCombatActionDescV2Args) -> Self {
        Self::ImportCombatActionDescV2 {
            records: args.records,
        }
    }
}

impl __sdk::InModule for ImportCombatActionDescV2Args {
    type Module = super::RemoteModule;
}

pub struct ImportCombatActionDescV2CallbackId(__sdk::CallbackId);

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `import_combat_action_desc_v2`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait import_combat_action_desc_v_2 {
    /// Request that the remote module invoke the reducer `import_combat_action_desc_v2` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed by listening for [`Self::on_import_combat_action_desc_v_2`] callbacks.
    fn import_combat_action_desc_v_2(&self, records: Vec<CombatActionDescV2>) -> __sdk::Result<()>;
    /// Register a callback to run whenever we are notified of an invocation of the reducer `import_combat_action_desc_v2`.
    ///
    /// Callbacks should inspect the [`__sdk::ReducerEvent`] contained in the [`super::ReducerEventContext`]
    /// to determine the reducer's status.
    ///
    /// The returned [`ImportCombatActionDescV2CallbackId`] can be passed to [`Self::remove_on_import_combat_action_desc_v_2`]
    /// to cancel the callback.
    fn on_import_combat_action_desc_v_2(
        &self,
        callback: impl FnMut(&super::ReducerEventContext, &Vec<CombatActionDescV2>) + Send + 'static,
    ) -> ImportCombatActionDescV2CallbackId;
    /// Cancel a callback previously registered by [`Self::on_import_combat_action_desc_v_2`],
    /// causing it not to run in the future.
    fn remove_on_import_combat_action_desc_v_2(&self, callback: ImportCombatActionDescV2CallbackId);
}

impl import_combat_action_desc_v_2 for super::RemoteReducers {
    fn import_combat_action_desc_v_2(&self, records: Vec<CombatActionDescV2>) -> __sdk::Result<()> {
        self.imp.call_reducer(
            "import_combat_action_desc_v2",
            ImportCombatActionDescV2Args { records },
        )
    }
    fn on_import_combat_action_desc_v_2(
        &self,
        mut callback: impl FnMut(&super::ReducerEventContext, &Vec<CombatActionDescV2>) + Send + 'static,
    ) -> ImportCombatActionDescV2CallbackId {
        ImportCombatActionDescV2CallbackId(self.imp.on_reducer(
            "import_combat_action_desc_v2",
            Box::new(move |ctx: &super::ReducerEventContext| {
                let super::ReducerEventContext {
                    event:
                        __sdk::ReducerEvent {
                            reducer: super::Reducer::ImportCombatActionDescV2 { records },
                            ..
                        },
                    ..
                } = ctx
                else {
                    unreachable!()
                };
                callback(ctx, records)
            }),
        ))
    }
    fn remove_on_import_combat_action_desc_v_2(
        &self,
        callback: ImportCombatActionDescV2CallbackId,
    ) {
        self.imp
            .remove_on_reducer("import_combat_action_desc_v2", callback.0)
    }
}

#[allow(non_camel_case_types)]
#[doc(hidden)]
/// Extension trait for setting the call-flags for the reducer `import_combat_action_desc_v2`.
///
/// Implemented for [`super::SetReducerFlags`].
///
/// This type is currently unstable and may be removed without a major version bump.
pub trait set_flags_for_import_combat_action_desc_v_2 {
    /// Set the call-reducer flags for the reducer `import_combat_action_desc_v2` to `flags`.
    ///
    /// This type is currently unstable and may be removed without a major version bump.
    fn import_combat_action_desc_v_2(&self, flags: __ws::CallReducerFlags);
}

impl set_flags_for_import_combat_action_desc_v_2 for super::SetReducerFlags {
    fn import_combat_action_desc_v_2(&self, flags: __ws::CallReducerFlags) {
        self.imp
            .set_call_reducer_flags("import_combat_action_desc_v2", flags);
    }
}
