// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::offset_coordinates_float_type::OffsetCoordinatesFloat;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct PlayerClimbRequest {
    pub destination: OffsetCoordinatesFloat,
    pub origin: OffsetCoordinatesFloat,
    pub timestamp: u64,
    pub climb_type: i32,
}

impl __sdk::InModule for PlayerClimbRequest {
    type Module = super::RemoteModule;
}
